{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0.aar",
          "url": "flutter_webrtc_debug-1.0.aar",
          "size": 204184,
          "sha512": "011a51a9bf42c52d12ccaf9456915183665b381a1282ec8d0a26cfa4ceeb5c419862f7360232dd7354d2c0fb08615de300a0aeb7b38a36c78ab26fca195bd68a",
          "sha256": "c53aa7c1833b4d28fcdd48f7a768f39a555cc5ae5ce15d7bd866a36fea984eac",
          "sha1": "0442ab5baba69e45e0f85eb7f38cc299a0de128f",
          "md5": "6d7fe0221f00b0fd05d06dcdf6c45343"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "125.6422.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0.aar",
          "url": "flutter_webrtc_debug-1.0.aar",
          "size": 204184,
          "sha512": "011a51a9bf42c52d12ccaf9456915183665b381a1282ec8d0a26cfa4ceeb5c419862f7360232dd7354d2c0fb08615de300a0aeb7b38a36c78ab26fca195bd68a",
          "sha256": "c53aa7c1833b4d28fcdd48f7a768f39a555cc5ae5ce15d7bd866a36fea984eac",
          "sha1": "0442ab5baba69e45e0f85eb7f38cc299a0de128f",
          "md5": "6d7fe0221f00b0fd05d06dcdf6c45343"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0-sources.jar",
          "url": "flutter_webrtc_debug-1.0-sources.jar",
          "size": 88593,
          "sha512": "7fffc48d97152e6517131487b03931032e7ceb141c7dd85e0588d697073d5b1f434ab20dafa310acaa718973c8ed4667e4a82cc27eb06d6ee117fd4c6ebd59c1",
          "sha256": "273b851928f0db3aa2a742960b9f8131db26e50303ac2cf8776520b6fd47d62c",
          "sha1": "845baefa526d68eb0db74e946aeea43e5c9901ee",
          "md5": "092b8705d417f60ba7ba1cfcf57cb772"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_debug-1.0-javadoc.jar",
          "url": "flutter_webrtc_debug-1.0-javadoc.jar",
          "size": 507028,
          "sha512": "3e8f2e7f9163dab0634aff0a5ecc9d521d6f7a7d671b17232ee4f720ab14e74fe9dcf8dbce439af79c1bdefab98a0839a02fea5d2f7197bd03a20094b53d0f6d",
          "sha256": "dce5351a116eb489ed1e00c194f5b85f287c7e826791a53a188d6f2f35630de2",
          "sha1": "875b40153e39f63e9fafc77f8e11cb689867b497",
          "md5": "d0f0dd72e92b61620abd4372037b85b0"
        }
      ]
    }
  ]
}
