{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cloudwebrtc.webrtc",
    "module": "flutter_webrtc_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-1.0.aar",
          "url": "flutter_webrtc_release-1.0.aar",
          "size": 193495,
          "sha512": "8abacae6d90af11f24f4526341d3ee3d0663606fcfe5d87778e031560e586addaab58ad66110ccd4c128174a1830f5f8b34b4c223eac1d9b217fc31600ef0fce",
          "sha256": "de59fcc5972f7a42ac43c834e8cb383904fa84238cd268a0358a7539b6e61052",
          "sha1": "d8c25247db15b7e607b916caede4b5662817728a",
          "md5": "38a93f739c3cdcd15d211ef88e632c4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-18b71d647a292a980abb405ac7d16fe1f0b20434"
          }
        },
        {
          "group": "io.github.webrtc-sdk",
          "module": "android",
          "version": {
            "requires": "125.6422.03"
          }
        },
        {
          "group": "com.github.davidliu",
          "module": "audioswitch",
          "version": {
            "requires": "89582c47c9a04c62f90aa5e57251af4800a62c9a"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_webrtc_release-1.0.aar",
          "url": "flutter_webrtc_release-1.0.aar",
          "size": 193495,
          "sha512": "8abacae6d90af11f24f4526341d3ee3d0663606fcfe5d87778e031560e586addaab58ad66110ccd4c128174a1830f5f8b34b4c223eac1d9b217fc31600ef0fce",
          "sha256": "de59fcc5972f7a42ac43c834e8cb383904fa84238cd268a0358a7539b6e61052",
          "sha1": "d8c25247db15b7e607b916caede4b5662817728a",
          "md5": "38a93f739c3cdcd15d211ef88e632c4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-1.0-sources.jar",
          "url": "flutter_webrtc_release-1.0-sources.jar",
          "size": 88593,
          "sha512": "7fffc48d97152e6517131487b03931032e7ceb141c7dd85e0588d697073d5b1f434ab20dafa310acaa718973c8ed4667e4a82cc27eb06d6ee117fd4c6ebd59c1",
          "sha256": "273b851928f0db3aa2a742960b9f8131db26e50303ac2cf8776520b6fd47d62c",
          "sha1": "845baefa526d68eb0db74e946aeea43e5c9901ee",
          "md5": "092b8705d417f60ba7ba1cfcf57cb772"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_webrtc_release-1.0-javadoc.jar",
          "url": "flutter_webrtc_release-1.0-javadoc.jar",
          "size": 507028,
          "sha512": "3e8f2e7f9163dab0634aff0a5ecc9d521d6f7a7d671b17232ee4f720ab14e74fe9dcf8dbce439af79c1bdefab98a0839a02fea5d2f7197bd03a20094b53d0f6d",
          "sha256": "dce5351a116eb489ed1e00c194f5b85f287c7e826791a53a188d6f2f35630de2",
          "sha1": "875b40153e39f63e9fafc77f8e11cb689867b497",
          "md5": "d0f0dd72e92b61620abd4372037b85b0"
        }
      ]
    }
  ]
}
